edutech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),    
    path('', include('home.urls')),
    path('student/', include('schools.urls')),
]

home/urls.py
from django.urls import path
from .views import home_view, school_directory_page


urlpatterns = [
    path('', home_view, name='home'),
    path('schools/', school_directory_page, name='schools')
]

school/urls.py
from school.views import index
from django.urls import path
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index)
]

schools/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('create-student/', StudentRegistrationView.as_view(), name='create-student'),
    path('create-teacher/', TeacherRegistrationView.as_view(), name='create_teacher'),
    path('create-class/', ClassRgeistraionView.as_view(), name='create-class'),
    path('create-subject/', SubjectRegistrationView.as_view(), name='create-subject'),
    path('create-exam/', ExamRegistrationView.as_view(), name='create-exam'),
    path('create-grade/', GradeRegistrationView.as_view(), name='create-grade'),
    path('', list_students, name='school')
]

schools/models.py
from django.db import models


class Student(models.Model):
    """Student Registration"""
    GENDER_CHOICES = [
        ('Male', 'Male'),
        ('Female', 'Female'),
    ]
    name = models.CharField(max_length=120)
    course = models.CharField()
    age = models.IntegerField()
    gender = models.CharField(choices=GENDER_CHOICES, default='Male')
    create_date = models.DateField(auto_now_add=True)
    
    
    def __str__(self):
        return self.name        

#Academic Management models
class Class(models.Model):
    name = models.CharField(max_length=50)
    section = models.CharField(max_length=10, blank=True, null=True)
    teacher = models.ForeignKey('Teacher', on_delete=models.SET_NULL, null=True,
                                related_name='classes')
    
    def __str__(self):
        return f"{self.name} {self.section}"
    
class Subject(models.Model):
    name = models.CharField(max_length=50)
    class_assigned = models.ForeignKey(Class, on_delete=models.CASCADE, related_name='subjects')
    
    def __str__(self):
        return self.name
    
class Teacher(models.Model):   
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class StudentSubject(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='subjects')
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='students')
    
    class Meta:
        unique_together = ('student', 'subject')
        
    def __str__(self):
        return f"{self.student} - {self.subject}"
    
    
class Exam(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='exams')
    exam_date = models.DateField()
    total_marks = models.PositiveIntegerField()
    
    def __str__(self):
        return f"Exam for {self.subject} on {self.exam_date} "
    
class Grade(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='grades')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='grades')
    marks_scored = models.PositiveIntegerField()
    
    def __str__(self):
        return f"{self.student} - {self.exam} - {self.marks_scored}"

schools/forms.py
from django import forms
from .models import *

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'course', 'gender', 'age']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'w-full p-2 border-4 border-gray-300 rounded-lg focus:ring-red-500 focus:border-sky-500 shadow-sm',
                'placeholder': 'Full Name..'
            }),
            'course': forms.TextInput(attrs={
                'class': 'w-full p-2 border-4 border-gray-300 rounded-lg focus:ring-red-500 focus:border-sky-500 shadow-sm',
                'placeholder': 'Course ..'
            }),
            'gender': forms.Select(attrs={
                'class': 'w-full p-2 border-4 border-gray-300 rounded-lg focus:ring-red-500 focus:border-sky-500 shadow-sm',
             }),
            'age': forms.NumberInput(attrs={
                'class': 'w-full p-2 border-4 border-gray-300 rounded-lg focus:ring-red-500 focus:border-sky-500 shadow-sm',
                'placeholder': 'Age ..'
            }),
        }
        
        labels = {
            'name': '',
            'course': '',
            'gender': '',
            'age': ''
        }


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'phone', 'email']
        

class ClassForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = ['name', 'section', 'teacher']
        

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields = ['name', 'class_assigned']
        
        
class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = ['subject', 'exam_date', 'total_marks']
        
        
class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ['exam', 'student', 'marks_scored']

school/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return HttpResponse("<h1>Public Index</h1>")

schools/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import *
from .forms import *

@login_required
def list_students(request):
    students = Student.objects.all()
    
    context = {
        'students': students,
    }
    return render(request, 'home_tenant.html', context)

class StudentRegistrationView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentForm    
    template_name = 'student_registration.html'
    success_url = reverse_lazy('school')
    
    
class TeacherRegistrationView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherForm
    template_name = 'teacher_reg_form.html'
    success_url = reverse_lazy('school')
    


class ClassRgeistraionView(LoginRequiredMixin, CreateView):
    model = Class
    form_class = ClassForm
    template_name = 'class_reg_form.html'
    success_url = reverse_lazy('school')
    
class SubjectRegistrationView(LoginRequiredMixin, CreateView):
    model = Subject
    form_class = SubjectForm
    template_name = 'subject_add_form.html'
    success_url = reverse_lazy('school')
    
    
class ExamRegistrationView(LoginRequiredMixin, CreateView):
    model = Exam
    form_class = ExamForm
    template_name = 'exam_add_form.html'
    success_url = reverse_lazy('school')
    
    
class GradeRegistrationView(LoginRequiredMixin, CreateView):
    model = Grade
    form_class = GradeForm
    template_name = 'grade_add_form.html'
    success_url = reverse_lazy('school')
    

schools/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SaaS Edutenant</title>
    <link href="{% static 'css/tailwind.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="https://img.icons8.com/glyph-neue/64/87CEEB/school.png" type="image/x-icon">
    
</head>
<body>
    
    <header class="flex items-center justify-between px-8 bg-sky-500 py-2 text-white sticky top-0 z-50">
        <logo>            
            <a href="/" class="flex items-center gap-1">
                <img class="h-12 mb-2" src="https://img.icons8.com/glyph-neue/64/ffffff/school.png" alt="school"/>
                <span>Edu Tech</span>
            </a>
        </logo>
        <nav>
            <ul class="flex items-center">
                {% if user.is_authenticated %}
                <li class="flex items-center h-12 px-4  hover:bg-sky-400 rounded-lg bg-sky-400"><a href="{% url 'schools' %}">Schools</a></li>               
                <li class="flex items-center h-12 px-4  hover:bg-sky-400 rounded-lg bg-sky-400"><a href="{% url 'account_logout' %}">Log Out</a></li>
 
                {% else %}
                <li class="flex items-center h-12 px-4  hover:bg-sky-400 rounded-lg bg-sky-400"><a href="{% url 'schools' %}">Schools</a></li> 
                <li class="flex items-center h-12 px-4  hover:bg-sky-400 rounded-lg bg-sky-400"><a href="{% url 'account_login' %}">Login</a></li>
                <li class="flex items-center h-12 px-4  hover:bg-sky-400 rounded-lg bg-sky-400"><a href="{% url 'account_signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
   {% block content %}
   {% endblock content %}

    <footer class="h-20 pt-5 bg-sky-200">
        <hr class=" my-4 border-gray-300">
        <p class="text-center font-mono text-gray-600">&copy;2025 Edutech SaaS. All rights rerseved.</p>
    </footer>
    
   
    
</body>
</html>

schools/templates/class_reg_form.html
{% extends 'base.html' %}

{% block content %}
<section class="flex items-center justify-center min-h-screen bg-sky-50">
    <div class="lg:w-1/3 p-8 bg-sky-200 rounded-xl shadow-lg">
        <h1 class="text-2xl font-bold text-center mb-6">Register Class</h1>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
            <!-- First_name field -->
            <div>
                <input type="text" name="name" id="id_name" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter class name" value="{{ form.name.value|default:'' }}">
                
                {% if form.name.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.name.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
             <!-- Last_name field -->
             <div>
                <input type="text" name="section" id="id_section" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter class section" value="{{ form.section.value|default:'' }}">
                
                {% if form.section.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.section.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            
               <!-- Teacher field -->
               <div>
                <select name="teacher" id="id_teacher" 
                        class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500">
                    <option value="" disabled selected>Select Teacher</option>
                    {% for teacher in form.teacher.field.queryset %}
                        <option value="{{ teacher.id }}" {% if teacher.id == form.teacher.value %} selected {% endif %}>
                            {{ teacher.first_name }} {{ teacher.last_name }}
                        </option>
                    {% endfor %}
                </select>

                {% if form.teacher.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.teacher.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
      
            <!-- Signup button -->
            <button type="submit" 
                    class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Register Class
            </button>
        </form>

    </div>
</section>
{% endblock content %}

schools/templates/exam_add_form.html
{% extends 'base.html' %}

{% block content %}
<section class="flex items-center justify-center min-h-screen bg-sky-50">
    <div class="lg:w-1/3 p-8 bg-sky-200 rounded-xl shadow-lg">
        <h1 class="text-2xl font-bold text-center mb-6">Register Exam</h1>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
                        
               <!-- Exam field -->
               <div>
                <select name="subject" id="id_subject" 
                        class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500">
                    <option value="" disabled selected>Select Class</option>
                    {% for subject in form.subject.field.queryset %}
                        <option value="{{ subject.id }}" {% if subject.id == form.subject.value %} selected {% endif %}>
                            {{ subject.name }}
                        </option>
                    {% endfor %}
                </select>

                {% if form.subject.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.subject.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
      
            <!-- exam date field -->
            <div>
                <input type="date" name="exam_date" id="id_exam_date" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter exam date" value="{{ form.exam_date.value|default:'' }}">
                
                {% if form.exam_date.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.exam_date.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            <!-- marks date field -->
            <div>
                <input type="number" name="total_marks" id="id_total_marks" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter marks" value="{{ form.total_marks.value|default:'' }}">
                
                {% if form.total_marks.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.total_marks.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <!-- Signup button -->
            <button type="submit" 
                    class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Register Exam
            </button>
        </form>

    </div>
</section>
{% endblock content %}

schools/templates/grade_add_form.html
{% extends 'base.html' %}

{% block content %}
<section class="flex items-center justify-center min-h-screen bg-sky-50">
    <div class="lg:w-1/3 p-8 bg-sky-200 rounded-xl shadow-lg">
        <h1 class="text-2xl font-bold text-center mb-6">Register Exam</h1>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
                        
               <!-- Exam field -->
               <div>
                <select name="exam" id="id_exam" 
                        class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500">
                    <option value="" disabled selected>Select Exam</option>
                    {% for exam in form.exam.field.queryset %}
                        <option value="{{ exam.id }}" {% if exam.id == form.subject.value %} selected {% endif %}>
                            {{ exam.subject }}
                        </option>
                    {% endfor %}
                </select>

                {% if form.exam.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.exam.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
      
            <!-- Exam field -->
            <div>
                <select name="student" id="id_student" 
                        class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500">
                    <option value="" disabled selected>Select Student</option>
                    {% for student in form.student.field.queryset %}
                        <option value="{{ student.id }}" {% if student.id == form.student.value %} selected {% endif %}>
                            {{ student.name }}
                        </option>
                    {% endfor %}
                </select>

                {% if form.student.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.student.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

           
         
            <!-- marks date field -->
            <div>
                <input type="number" name="marks_scored" id="id_marks_scored" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter marks" value="{{ form.marks_scored.value|default:'' }}">
                
                {% if form.marks_scored.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.marks_scored.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            <!-- Signup button -->
            <button type="submit" 
                    class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Register Exam
            </button>
        </form>

    </div>
</section>
{% endblock content %}

schools/templates/home_tenant.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="flex justify-center min-h-screen">
    <div class="bg-sky-50 pt-24 w-full md:px-20 sm:px-4">
        <table class="table-auto border border-collapse border-gray-300 shadow-lg  pt-11 w-full">
            <caption class="caption-top pb-5 font-mono">
                Registered Students <span class="bg-sky-400 p-2 rounded-md text-white hover:bg-sky-300 shadow-lg"><a href="{% url 'create-student' %}">Add Student</a></span>
              </caption>
            <thead class="border-b rounded-2xl">
                <tr class="py-15 bg-sky-200">
                    <th class="py-5 font-mono">Name</th>
                    <th class="py-5 font-mono">Course</th>
                    <th class="py-5 font-mono">Gender</th>
                    <th class="py-5 font-mono">Age</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr class="border-b even:bg-sky-50 odd:bg-white hover:bg-sky-100">
                    <td class="py-3 px-4">{{ student.name }}</td>
                   <td class="py-3 px-4"> {{ student.course }}</td>
                   <td class="py-3 px-4"> {{ student.gender }}</td>
                    <td class="py-3 px-4">{{ student.age }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock content %}

schools/templates/student_registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<section class="relative flex flex-col lg:flex-row items-center min-h-screen bg-sky-100 pb-8">
    <div  class="basis-full lg:px-20 pt-14 px-4">
        <h1 class="text-2xl font-semibold text-center lg:text-start">{{  request.tenant.name }}</h1>
        <p class="pt-5 font-sans text-justify"><span class="font-mono">{{ request.tenant.name }} </span> is using Edu Tenant  a cloud-based platform designed to simplify the student registration process. 
            It provides a streamlined and efficient way for <span class="font-mono underline">{{ request.tenant.name }}</span> to manage student registrations online, 
            eliminating manual paperwork and reducing administrative workload.</p>
    </div>
    <div id="form" class=" mt-16 p-8 bg-sky-50 rounded-xl shadow-lg basis-full lg:mr-32">
        <h1 class="text-3xl text-center mb-6">Register Student</h1>
        
        <form  method="post" class="space-y-6">
            {% csrf_token %}
            
            {{ form.as_p }}                

            <button type="submit" class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">Register Student</button>
        </form>
    </div>
</section>


{% endblock content %}

schools/templates/subject_add_form.html
{% extends 'base.html' %}

{% block content %}
<section class="flex items-center justify-center min-h-screen bg-sky-50">
    <div class="lg:w-1/3 p-8 bg-sky-200 rounded-xl shadow-lg">
        <h1 class="text-2xl font-bold text-center mb-6">Register Subject</h1>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
            <!-- First_name field -->
            <div>
                <input type="text" name="name" id="id_name" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter Subject name" value="{{ form.name.value|default:'' }}">
                
                {% if form.name.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.name.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            
            
               <!-- Teacher field -->
               <div>
                <select name="class_assigned" id="id_class_assigned" 
                        class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500">
                    <option value="" disabled selected>Select Class</option>
                    {% for class_assigned in form.class_assigned.field.queryset %}
                        <option value="{{ class_assigned.id }}" {% if class_assigned.id == form.class_assigned.value %} selected {% endif %}>
                            {{ class_assigned.name }}
                        </option>
                    {% endfor %}
                </select>

                {% if form.class_assigned.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.class_assigned.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
      
            <!-- Signup button -->
            <button type="submit" 
                    class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Register Subject
            </button>
        </form>

    </div>
</section>
{% endblock content %}

schools/templates/teacher_reg_form.html
{% extends 'base.html' %}

{% block content %}
<section class="flex items-center justify-center min-h-screen bg-sky-50">
    <div class="lg:w-1/3 p-8 bg-sky-200 rounded-xl shadow-lg">
        <h1 class="text-2xl font-bold text-center mb-6">Register Teacher</h1>
        
        <form method="post" class="space-y-6">
            {% csrf_token %}
            
            <!-- First_name field -->
            <div>
                <input type="text" name="first_name" id="id_first_name" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter your first name" value="{{ form.first_name.value|default:'' }}">
                
                {% if form.first_name.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.first_name.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
             <!-- Last_name field -->
             <div>
                <input type="text" name="last_name" id="id_last_name" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter your last name" value="{{ form.last_name.value|default:'' }}">
                
                {% if form.last_name.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.last_name.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

            
            <!-- Email field -->
            <div>
                <input type="email" name="email" id="id_email" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter your email" value="{{ form.email.value|default:'' }}">
                
                {% if form.email.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.email.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>

             <!-- Phone field -->
             <div>
                <input type="text" name="phone" id="id_phone" 
                       class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-sky-500 focus:border-sky-500" 
                       placeholder="Enter your phone" value="{{ form.phone.value|default:'' }}">
                
                {% if form.phone.errors %}
                    <div class="text-red-500 text-sm">
                        {% for error in form.phone.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
            

            <!-- Signup button -->
            <button type="submit" 
                    class="w-full bg-sky-400 py-2 rounded-md text-white hover:bg-sky-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-sky-500">
                Register Teacher
            </button>
        </form>

    </div>
</section>
{% endblock content %}